# Generated by Django 3.0.3 on 2020-03-31 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user_name',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='introduction',
            field=models.TextField(default='INTRODUCTION', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
