# Generated by Django 3.0.3 on 2020-04-02 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0003_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post',
            field=models.TextField(blank=True, default="What's new today? Share with Grumbler!", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
