# Generated by Django 3.0.3 on 2020-04-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_auto_20200402_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post_pic',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='username',
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
