# Generated by Django 3.0.3 on 2020-04-08 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_auto_20200405_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post',
            field=models.TextField(blank=True, default='', max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 3, 18, 52, 657089, tzinfo=utc)),
        ),
    ]
