# Generated by Django 3.0.3 on 2020-04-08 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0010_auto_20200408_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 7, 28, 48, 59693, tzinfo=utc)),
        ),
    ]
