# Generated by Django 3.0.3 on 2020-04-10 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0012_auto_20200408_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 2, 9, 50, 571659, tzinfo=utc)),
        ),
    ]
