# Generated by Django 3.0.3 on 2020-04-10 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0015_auto_20200410_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 8, 36, 43, 723440, tzinfo=utc)),
        ),
    ]
