# Generated by Django 3.0.3 on 2020-04-12 02:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0017_auto_20200411_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 2, 51, 0, 896763, tzinfo=utc)),
        ),
    ]
