# Generated by Django 3.0.3 on 2020-04-14 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0018_auto_20200412_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
